### ISSUE TITLE
Update document on xOpera install and usage

### ISSUE THREAD

**Issue by KalmanMeth** [SODALITE-EU/iac-blueprint-builder#31]
In the document https://docs.google.com/document/d/1EAxDcDutx1C4opGp6dI-t_d-RXVjUoFurclxA_rslRM/edit# on xOpera installation and usage:
The section on "Adding public ssh key to OpenStack" uses the command "openstack".
The "openstack" command is only introduced in the next section "Optional install openstack client".
The order of the sections should be reversed.

**Comment by dradX** [comment]
Done
